import React, { useLayoutEffect, useRef, useState } from 'react';

/**
 * A single thin sketch line over the untouched production Cover: the hand
 * touching the official record, the gesture already living in the Kylie
 * key art's scribbled crown and in Visual Audiobooks' written-by-hand,
 * drawn-by-code. The line draws itself once on arrival (machine-drawn),
 * then holds still. Reduced motion renders it fully drawn.
 *
 * The paths are a stand-in hand: any real pen line of Jeanine's can
 * replace them by swapping the path data, no other code changes.
 */

export type SketchKind = 'profile' | 'emerging' | 'duet';

/* One continuous contour line, a profile facing into the page.
   Front contour only, in the iconic-silhouette register: few curves,
   drawn once, no back-of-head loop. */
const PROFILE_D =
  'M 210 -330 C 290 -318 336 -258 342 -178 C 347 -114 340 -52 328 -4 C 315 42 300 90 290 138 C 286 152 276 158 273 170 C 268 186 244 240 228 276 C 222 288 220 298 228 303 C 238 310 250 308 252 318 C 253 328 248 332 250 340 C 262 346 269 354 264 366 C 259 375 253 379 256 388 C 267 394 274 403 268 417 C 262 428 257 435 262 447 C 272 464 286 476 295 492 C 310 520 330 536 358 550 C 370 560 375 574 376 594 C 379 640 375 692 385 736 C 393 760 407 772 427 780';

/* A wandering line that only becomes a face at its end. */
const MEANDER_D =
  'M -20 470 C 120 440 210 500 330 468 C 450 436 540 502 660 470 C 740 448 800 470 860 452';

/* One line, never lifting: down through the first profile, across the
   valley between them, up into the second. Generated by mirroring and
   reversing PROFILE_D so the two faces stay identical twins. */
const DUET_D =
  'M 440 -330 C 360 -318 314 -258 308 -178 C 303 -114 310 -52 322 -4 C 335 42 350 90 360 138 C 364 152 374 158 377 170 C 382 186 406 240 422 276 C 428 288 430 298 422 303 C 412 310 400 308 398 318 C 397 328 402 332 400 340 C 388 346 381 354 386 366 C 391 375 397 379 394 388 C 383 394 376 403 382 417 C 388 428 393 435 388 447 C 378 464 364 476 355 492 C 340 520 320 536 292 550 C 280 560 275 574 274 594 C 271 640 275 692 265 736 C 257 760 243 772 223 780 C 313 814 340 826 480 828 C 640 830 780 830 920 826 C 1020 822 1097 810 1127 780 C 1107 772 1093 760 1085 736 C 1075 692 1079 640 1076 594 C 1075 574 1070 560 1058 550 C 1030 536 1010 520 995 492 C 986 476 972 464 962 447 C 957 435 962 428 968 417 C 974 403 967 394 956 388 C 953 379 959 375 964 366 C 969 354 962 346 950 340 C 948 332 953 328 952 318 C 950 308 938 310 928 303 C 920 298 922 288 928 276 C 944 240 968 186 973 170 C 976 158 986 152 990 138 C 1000 90 1015 42 1028 -4 C 1040 -52 1047 -114 1042 -178 C 1036 -258 990 -318 910 -330';

const Path: React.FC<{ d: string; delay?: number; duration?: number }> = ({
  d,
  delay = 0.6,
  duration = 2.6,
}) => (
  <path
    d={d}
    pathLength={1}
    style={{ animationDelay: `${delay}s`, animationDuration: `${duration}s` }}
  />
);

/* The line breaks where the name crosses it: it stops at the headline's
   band and resumes beneath it, so the type always wins. The band is
   measured from the section's own h1, not guessed. */
const useNameBandMask = (wrapRef: React.RefObject<HTMLDivElement | null>) => {
  const [band, setBand] = useState<[number, number] | null>(null);

  useLayoutEffect(() => {
    const wrap = wrapRef.current;
    const section = wrap?.closest('section');
    const h1 = section?.querySelector('h1');
    if (!wrap || !section || !h1) return;
    const measure = () => {
      const s = section.getBoundingClientRect();
      const n = h1.getBoundingClientRect();
      const pad = 18;
      setBand([Math.max(0, n.top - s.top - pad), n.bottom - s.top + pad]);
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(section);
    ro.observe(h1);
    return () => ro.disconnect();
  }, [wrapRef]);

  return band
    ? `linear-gradient(180deg, black 0, black ${band[0]}px, transparent ${band[0]}px, transparent ${band[1]}px, black ${band[1]}px, black 100%)`
    : undefined;
};

const ProfileOverlay: React.FC<{ cls: string }> = ({ cls }) => {
  const wrapRef = useRef<HTMLDivElement>(null);
  const mask = useNameBandMask(wrapRef);

  return (
    <div
      ref={wrapRef}
      aria-hidden="true"
      className="absolute inset-0 pointer-events-none overflow-hidden"
      style={{ maskImage: mask, WebkitMaskImage: mask }}
    >
      {/* Sized so the crown shows above the headline, the band breaks the
          line, and the face itself sits fully below on real viewports. */}
      {/* The pen starts after the name has set itself: type first, then
          the hand. */}
      <svg
        className={`${cls} absolute right-[2%] top-[9%] h-[89%] w-[46%] min-w-[320px]`}
        viewBox="0 -400 600 1300"
        preserveAspectRatio="xMidYMin meet"
      >
        <Path d={PROFILE_D} delay={1.9} duration={3.2} />
      </svg>
    </div>
  );
};

export const SketchLineOverlay: React.FC<{ kind: SketchKind }> = ({ kind }) => {
  const [reduced] = useState(
    () =>
      typeof window !== 'undefined' &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches
  );
  const cls = `hero-sketch${reduced ? '' : ' hero-sketch--animate'}`;

  if (kind === 'profile') {
    return <ProfileOverlay cls={cls} />;
  }

  if (kind === 'emerging') {
    return (
      <div aria-hidden="true" className="absolute inset-0 pointer-events-none overflow-hidden">
        <svg
          className={`${cls} absolute inset-0 h-full w-full`}
          viewBox="0 0 1600 900"
          preserveAspectRatio="xMidYMid meet"
        >
          <Path d={MEANDER_D} delay={0.6} duration={1.3} />
          <g transform="translate(830, 120) scale(0.78)">
            <Path d={PROFILE_D} delay={1.9} duration={2.4} />
          </g>
        </svg>
      </div>
    );
  }

  return <DuetOverlay cls={cls} />;
};

/* duet: one continuous line, down through the first profile, across,
   and up into the second. Same name-band break as the single profile. */
const DuetOverlay: React.FC<{ cls: string }> = ({ cls }) => {
  const wrapRef = useRef<HTMLDivElement>(null);
  const mask = useNameBandMask(wrapRef);

  return (
    <div
      ref={wrapRef}
      aria-hidden="true"
      className="absolute inset-0 pointer-events-none overflow-hidden"
      style={{ maskImage: mask, WebkitMaskImage: mask }}
    >
      <svg
        className={`${cls} absolute left-1/2 top-[9%] h-[89%] w-[74%] min-w-[380px] -translate-x-1/2`}
        viewBox="0 -400 1350 1300"
        preserveAspectRatio="xMidYMin meet"
      >
        <Path d={DUET_D} delay={1.9} duration={5.6} />
      </svg>
    </div>
  );
};
